package com.aem.mahout.core.servlets;

import com.aem.mahout.core.services.RecommenderService;
import org.apache.felix.scr.annotations.Reference;
import org.apache.felix.scr.annotations.sling.SlingServlet;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.SlingHttpServletResponse;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.servlets.SlingAllMethodsServlet;

import javax.servlet.ServletException;
import java.io.IOException;



@SlingServlet(paths = "/bin/recommend/mahout")
public class RecommenderServlet extends SlingAllMethodsServlet {

    @Reference
    private RecommenderService recommenderService;

    @Override
    protected void doGet(final SlingHttpServletRequest req,
                         final SlingHttpServletResponse resp) throws ServletException, IOException {

        recommenderService.showRecommendations();
        resp.getOutputStream().println(
                "This content is generated by the RecommenderServlet");
    }


}
